import { html } from './http';
import { randomToken } from './crypto';

export function operationsUi(): Response {
  const nonce = randomToken(12);
  const markup = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Central operacional — PJJ</title><style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;background:#f4f2ed;color:#181818;font:14px system-ui}.top{padding:18px 5vw;background:#090909;color:#fff;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #bd8b2955}.top a{color:#fff}.main{width:min(1200px,92%);margin:30px auto}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.card,.panel{background:#fff;border:1px solid #dfdbd2;border-radius:14px;padding:18px;box-shadow:0 7px 24px #0000000b}.card strong{display:block;font-size:28px;margin-top:7px}.panel{margin-top:20px;overflow:auto}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.tabs button,.action{border:0;border-radius:8px;padding:9px 12px;background:#090909;color:#fff;cursor:pointer;text-decoration:none}.action.alt{background:#fff;color:#181818;border:1px solid #dfdbd2}.action.danger{background:#96382f}.tabs button.active{background:#bd8b29}.table{min-width:820px}.row{display:grid;grid-template-columns:1.3fr 1.1fr .8fr 1.2fr;gap:12px;align-items:center;padding:11px;border-bottom:1px solid #e4dfd5}.actions{display:flex;gap:7px;justify-content:flex-end}.muted{color:#706b62}.bad{color:#9b332d}@media(max-width:700px){.main{width:94%}.top{padding:15px 3%}}
</style></head><body><header class="top"><strong>PJJ · Central operacional</strong><a href="/admin">← Painel principal</a></header><main class="main"><h1>Operação, acessos e auditoria</h1><div class="cards" id="summary"></div><nav class="tabs"><button data-tab="jobs" class="active">Processamento</button><button data-tab="assets">Produtos</button><button data-tab="grants">Compartilhamentos</button><button data-tab="embeds">Embeds</button><button data-tab="sessions">Sessões</button><button data-tab="audit">Auditoria</button></nav><section class="panel"><div id="content">Carregando…</div></section></main><script nonce="${nonce}">
let overview,access,audit,csrf='';const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(p,o={}){o.headers={'content-type':'application/json',...(csrf?{'x-csrf-token':csrf}:{}),...(o.headers||{})};const r=await fetch(p,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error?.message||'Falha'),{status:r.status});return d}
function genericRows(items,kind){if(!items?.length)return'<p class="muted">Nenhum registro.</p>';return'<div class="table">'+items.map(x=>'<div class="row"><strong>'+esc(x.label||x.name||x.email||x.action||x.id)+'</strong><span>'+esc(x.project_name||x.target_type||x.status||'—')+'</span><span class="muted">'+esc(x.expires_at||x.created_at||x.updated_at||'—')+'</span><span class="actions">'+(kind&&!x.revoked_at?'<button class="action danger" data-revoke="'+kind+'" data-id="'+x.id+'">Revogar</button>':esc(x.outcome||x.permission||x.status||''))+'</span></div>').join('')+'</div>'}
function jobRows(items){if(!items?.length)return'<p class="muted">Fila vazia.</p>';return'<div class="table">'+items.map(x=>'<div class="row"><strong>'+esc(x.asset_title)+'</strong><span>'+esc(x.type)+' · '+esc(x.progress)+'%</span><span class="'+(x.status==='failed'?'bad':'muted')+'">'+esc(x.status)+(x.error_message?'<br><small>'+esc(x.error_message)+'</small>':'')+'</span><span class="actions">'+(x.status==='failed'?'<button class="action" data-retry="'+x.id+'">Reprocessar</button>':'')+'</span></div>').join('')+'</div>'}
function assetRows(items){if(!items?.length)return'<p class="muted">Nenhum produto.</p>';return'<div class="table">'+items.map(x=>'<div class="row"><strong>'+esc(x.title)+'</strong><span>'+esc(x.project_name)+' · '+esc(x.type)+'</span><span class="'+(x.status==='failed'?'bad':'muted')+'">'+esc(x.status)+'</span><span class="actions">'+(x.status==='review'?'<a class="action" href="/admin/review/'+x.id+'">Revisar</a>':'')+(x.status==='published'?'<a class="action alt" href="/viewer/'+x.id+'">Abrir</a>':'')+'<button class="action danger" data-trash="'+x.id+'">Excluir</button></span></div>').join('')+'</div>'}
function bindActions(tab){document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{if(!confirm('Revogar este acesso agora?'))return;await api('/api/admin/'+b.dataset.revoke+'s/'+b.dataset.id+'/revoke',{method:'POST'});await load();show(tab)});document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=async()=>{await api('/api/admin/jobs/'+b.dataset.retry+'/retry',{method:'POST'});await load();show('jobs')});document.querySelectorAll('[data-publish]').forEach(b=>b.onclick=async()=>{await api('/api/admin/assets/'+b.dataset.publish+'/publish',{method:'POST'});await load();show('assets')});document.querySelectorAll('[data-trash]').forEach(b=>b.onclick=async()=>{if(!confirm('Mover este produto para a lixeira do Drive? A exclusão é recuperável.'))return;await api('/api/admin/assets/'+b.dataset.trash,{method:'DELETE'});await load();show('assets')})}
function show(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='jobs')$('#content').innerHTML='<h2>Fila de processamento</h2>'+jobRows(overview.jobs);else if(tab==='assets')$('#content').innerHTML='<h2>Produtos</h2>'+assetRows(overview.assets);else if(tab==='audit')$('#content').innerHTML='<h2>Eventos recentes</h2>'+genericRows(audit.items);else $('#content').innerHTML='<h2>'+({grants:'Compartilhamentos',embeds:'Embeds',sessions:'Sessões'})[tab]+'</h2>'+genericRows(access[tab],tab.slice(0,-1));bindActions(tab)}
async function load(){try{[overview,access,audit]=await Promise.all([api('/api/admin/overview'),api('/api/admin/access'),api('/api/admin/audit?limit=100')]);const counts=overview.counts||{};$('#summary').innerHTML=Object.entries(counts).map(([k,v])=>'<div class="card"><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join('');show(document.querySelector('[data-tab].active')?.dataset.tab||'jobs')}catch(e){if(e.status===401)location.href='/admin';else $('#content').innerHTML='<p class="bad">'+esc(e.message)+'</p>'}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));api('/api/auth/me').then(me=>{csrf=me.csrfToken;return load()}).catch(()=>location.href='/admin');
</script></body></html>`;
  return html(markup, nonce);
}
