import type { Env } from './env';
import type { Principal } from './auth';
import { error, html } from './http';
import { randomToken } from './crypto';

function esc(v:unknown):string{return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}

export async function viewerPage(env:Env,actor:Principal,assetId:string,rid:string):Promise<Response>{
  const asset=await env.DB.prepare(`SELECT a.id,a.type,a.title,a.mime_type,a.status,a.metadata_json FROM assets a JOIN projects p ON p.id=a.project_id
    WHERE a.id=?1 AND a.status!='trashed' AND (?2 IN ('owner','admin') OR (a.status='published' AND EXISTS(SELECT 1 FROM project_members m WHERE m.project_id=p.id AND m.user_id=?3)))`)
    .bind(assetId,actor.role,actor.userId).first<{id:string;type:string;title:string;mime_type:string|null;status:string;metadata_json:string|null}>();
  if(!asset)return error(404,'asset_not_found','Produto não encontrado.',rid);
  const preferred=asset.type==='model_3d'?'optimized_glb':asset.type==='point_cloud'?'copc':['orthophoto','dsm','dtm'].includes(asset.type)?'cog':null;
  const variant=preferred?await env.DB.prepare("SELECT variant_type FROM asset_variants WHERE asset_id=?1 AND variant_type=?2 AND status='ready'").bind(assetId,preferred).first():null;
  const content=`/api/portal/assets/${assetId}/content${variant?`?variant=${preferred}`:'?inline=1'}`;
  const nonce=randomToken(12);let module='';
  if(['orthophoto','dsm','dtm'].includes(asset.type)&&variant){module=`import{fromUrl}from'https://esm.sh/geotiff@2.1.3';const status=document.querySelector('#status'),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');try{const tif=await fromUrl('${content}'),image=await tif.getImage(),w=image.getWidth(),h=image.getHeight(),maxSide=(navigator.deviceMemory||4)<=4||navigator.connection?.saveData?1200:2200,scale=Math.min(1,maxSide/Math.max(w,h)),ow=Math.max(1,Math.round(w*scale)),oh=Math.max(1,Math.round(h*scale)),r=await image.readRasters({width:ow,height:oh,interleave:true,resampleMethod:'bilinear'}),samples=image.getSamplesPerPixel(),out=new Uint8ClampedArray(ow*oh*4);let min=Infinity,max=-Infinity;if(samples===1){for(const v of r){if(Number.isFinite(v)){min=Math.min(min,v);max=Math.max(max,v)}}}for(let i=0;i<ow*oh;i++){if(samples===1){const v=Math.round(255*(r[i]-min)/(max-min||1));out[i*4]=out[i*4+1]=out[i*4+2]=v}else{out[i*4]=r[i*samples];out[i*4+1]=r[i*samples+1]??r[i*samples];out[i*4+2]=r[i*samples+2]??r[i*samples]}out[i*4+3]=255}canvas.width=ow;canvas.height=oh;ctx.putImageData(new ImageData(out,ow,oh),0,0);status.textContent=w+' × '+h+' px · '+(maxSide===1200?'modo leve':'alta qualidade')}catch(e){status.textContent='Falha ao abrir o COG: '+e.message}`}
  else if(asset.type==='model_3d'&&variant){module=`import*as THREE from'https://esm.sh/three@0.180.0';import{GLTFLoader}from'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';import{OrbitControls}from'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js';const host=document.querySelector('#stage'),scene=new THREE.Scene();scene.background=new THREE.Color(0x101916);const camera=new THREE.PerspectiveCamera(45,host.clientWidth/host.clientHeight,.01,1e7),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(host.clientWidth,host.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x33443e,3));const controls=new OrbitControls(camera,renderer.domElement);new GLTFLoader().load('${content}',g=>{scene.add(g.scene);const box=new THREE.Box3().setFromObject(g.scene),size=box.getSize(new THREE.Vector3()).length(),center=box.getCenter(new THREE.Vector3());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.6,size*.45,size*.6));camera.near=size/10000;camera.far=size*100;camera.updateProjectionMatrix();controls.update();document.querySelector('#status').textContent='Modelo carregado'},undefined,e=>document.querySelector('#status').textContent='Falha: '+e.message);function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop();addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)})`}
  else if(asset.type==='point_cloud'&&variant){module=`import*as THREE from'https://esm.sh/three@0.180.0';import{OrbitControls}from'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js';import{Copc,Getter}from'https://esm.sh/copc';const host=document.querySelector('#stage'),status=document.querySelector('#status'),scene=new THREE.Scene(),pointLimit=(navigator.deviceMemory||4)<=4||navigator.connection?.saveData?250000:750000;scene.background=new THREE.Color(0x0d1613);const camera=new THREE.PerspectiveCamera(50,host.clientWidth/host.clientHeight,.01,1e9),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(host.clientWidth,host.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);try{const getter=Getter.http('${content}'),copc=await Copc.create(getter),hierarchy=await Copc.loadHierarchyPage(getter,copc.info.rootHierarchyPage),nodes=Object.values(hierarchy.nodes||hierarchy).filter(n=>n&&n.pointCount).sort((a,b)=>a.key.split('-')[0]-b.key.split('-')[0]),positions=[],colors=[];let count=0;for(const node of nodes){if(count>=pointLimit)break;const view=await Copc.loadPointDataView(getter,copc.info,node),x=view.getter('X'),y=view.getter('Y'),z=view.getter('Z'),red=view.getter('Red'),green=view.getter('Green'),blue=view.getter('Blue'),limit=Math.min(view.pointCount||node.pointCount,pointLimit-count);for(let i=0;i<limit;i++){positions.push(x(i),y(i),z(i));colors.push((red?.(i)??65535)/65535,(green?.(i)??65535)/65535,(blue?.(i)??65535)/65535)}count+=limit}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.computeBoundingBox();const cloud=new THREE.Points(geometry,new THREE.PointsMaterial({size:1,vertexColors:true,sizeAttenuation:true}));scene.add(cloud);const box=geometry.boundingBox,size=box.getSize(new THREE.Vector3()).length(),center=box.getCenter(new THREE.Vector3());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.55,size*.4,size*.55));camera.near=size/100000;camera.far=size*100;camera.updateProjectionMatrix();controls.update();status.textContent=count.toLocaleString('pt-BR')+' pontos carregados'+(pointLimit===250000?' · modo leve':'')}catch(e){status.textContent='Falha ao abrir COPC: '+e.message}function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop();addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)})`}
  else if(asset.type==='photo')module=`document.querySelector('#stage').innerHTML='<img class="media" src="${content}" alt="">';document.querySelector('#status').textContent='Imagem'`;
  else if(asset.type==='video')module=`document.querySelector('#stage').innerHTML='<video class="media" src="${content}" controls></video>';document.querySelector('#status').textContent='Vídeo'`;
  else if(asset.type==='pdf'||asset.type==='document')module=`document.querySelector('#stage').innerHTML='<iframe class="media" src="${content}" title="Documento"></iframe>';document.querySelector('#status').textContent='Documento'`;
  else module=`document.querySelector('#status').textContent='A variante de visualização ainda não foi gerada.'`;
  if(['orthophoto','dsm','dtm'].includes(asset.type)&&variant)module+=`;const reset=document.createElement('button');reset.textContent='Resetar';reset.style.cssText='padding:8px;border:0;border-radius:6px';document.querySelector('.bar').append(reset);let zoom=1,px=0,py=0,drag=false,sx=0,sy=0;const c=document.querySelector('canvas');function transform(){c.style.transform='translate('+px+'px,'+py+'px) scale('+zoom+')';c.style.transformOrigin='center'}document.querySelector('#stage').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.25,Math.min(12,zoom*(e.deltaY<0?1.18:.85)));transform()},{passive:false});c.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX-px;sy=e.clientY-py;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(drag){px=e.clientX-sx;py=e.clientY-sy;transform()}});c.addEventListener('pointerup',()=>drag=false);reset.onclick=()=>{zoom=1;px=py=0;transform()}`;
  if(asset.type==='model_3d'&&variant)module+=`;const reset3d=document.createElement('button');reset3d.textContent='Resetar câmera';reset3d.className='tool';document.querySelector('.tools').append(reset3d);reset3d.onclick=()=>{const box=new THREE.Box3().setFromObject(scene),size=box.getSize(new THREE.Vector3()).length(),center=box.getCenter(new THREE.Vector3());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.6,size*.45,size*.6));controls.update()};const grid=new THREE.GridHelper(100,20,0xb8872c,0x555555);grid.visible=false;scene.add(grid);const gridButton=document.createElement('button');gridButton.textContent='Grade';gridButton.className='tool';document.querySelector('.tools').append(gridButton);gridButton.onclick=()=>grid.visible=!grid.visible`;
  if(asset.type==='point_cloud'&&variant)module+=`;const sizeControl=document.createElement('input');sizeControl.type='range';sizeControl.min='.2';sizeControl.max='5';sizeControl.step='.2';sizeControl.value='1';sizeControl.title='Tamanho dos pontos';document.querySelector('.tools').append(sizeControl);sizeControl.oninput=()=>{const cloud=scene.children.find(x=>x.isPoints);if(cloud)cloud.material.size=Number(sizeControl.value)}`;
  module+=`;const full=document.createElement('button');full.textContent='Tela cheia';full.className='tool';document.querySelector('.tools').append(full);full.onclick=()=>document.querySelector('#stage').requestFullscreen?.();const info=document.createElement('button');info.textContent='Informações';info.className='tool';document.querySelector('.tools').append(info);info.onclick=()=>document.querySelector('#metadata').showModal()`;
  const markup=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(asset.title)} — PJJ</title><style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#0a0a0a;color:#fff;font:14px system-ui;overflow:hidden}.bar{min-height:64px;display:flex;align-items:center;gap:14px;padding:9px 18px;background:#090909;border-bottom:1px solid #b8872c55}.bar h1{font-size:16px;margin-right:auto}.bar a{color:#fff}.tools{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.tool{padding:8px 10px;border:1px solid #ffffff2b;border-radius:7px;background:#1b1b1b;color:#fff;cursor:pointer}.stage{height:calc(100vh - 100px);display:grid;place-items:center;overflow:hidden;touch-action:none}.stage canvas{max-width:none;image-rendering:auto;box-shadow:0 10px 50px #0008}.media{width:100%;height:100%;object-fit:contain;border:0}.status{height:36px;padding:8px 18px;color:#d5c7aa;background:#111}dialog{width:min(680px,calc(100% - 30px));border:0;border-radius:14px;padding:22px}dialog pre{white-space:pre-wrap;max-height:60vh;overflow:auto;font-size:11px}@media(max-width:700px){.bar{align-items:flex-start;flex-direction:column}.bar h1{margin:0}.stage{height:calc(100vh - 150px)}.status{height:42px}}</style></head><body><header class="bar"><h1>${esc(asset.title)}</h1><div class="tools"><a class="tool" href="${content}">Baixar original</a></div></header><main id="stage" class="stage"><canvas></canvas></main><footer id="status" class="status">Carregando…</footer><dialog id="metadata"><h2>Informações do produto</h2><pre>${esc(asset.metadata_json||'{}')}</pre><button class="tool" onclick="this.closest('dialog').close()">Fechar</button></dialog><script type="module" nonce="${nonce}">${module}</script></body></html>`;
  const response=html(markup,nonce);response.headers.set('content-security-policy',`default-src 'none'; script-src 'nonce-${nonce}' https://esm.sh; connect-src 'self' https://esm.sh; img-src 'self' blob: data:; media-src 'self' blob:; frame-src 'self'; style-src 'nonce-${nonce}'; frame-ancestors 'self'; base-uri 'none'`);response.headers.delete('x-frame-options');return response;
}
