import type { Env } from './env';
import type { Principal } from './auth';
import { error, html } from './http';
import { randomToken } from './crypto';

function esc(v:unknown):string{return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}

export async function viewerPage(env:Env,actor:Principal,assetId:string,rid:string):Promise<Response>{
  const asset=await env.DB.prepare(`SELECT a.id,a.type,a.title,a.mime_type,a.status FROM assets a JOIN projects p ON p.id=a.project_id
    WHERE a.id=?1 AND a.status!='trashed' AND (?2 IN ('owner','admin') OR (a.status='published' AND EXISTS(SELECT 1 FROM project_members m WHERE m.project_id=p.id AND m.user_id=?3)))`)
    .bind(assetId,actor.role,actor.userId).first<{id:string;type:string;title:string;mime_type:string|null;status:string}>();
  if(!asset)return error(404,'asset_not_found','Produto não encontrado.',rid);
  const preferred=asset.type==='model_3d'?'optimized_glb':asset.type==='point_cloud'?'copc':['orthophoto','dsm','dtm'].includes(asset.type)?'cog':null;
  const variant=preferred?await env.DB.prepare("SELECT variant_type FROM asset_variants WHERE asset_id=?1 AND variant_type=?2 AND status='ready'").bind(assetId,preferred).first():null;
  const content=`/api/portal/assets/${assetId}/content${variant?`?variant=${preferred}`:'?inline=1'}`;
  const nonce=randomToken(12);let module='';
  if(['orthophoto','dsm','dtm'].includes(asset.type)&&variant){module=`import{fromUrl}from'https://esm.sh/geotiff@2.1.3';const status=document.querySelector('#status'),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');try{const tif=await fromUrl('${content}'),image=await tif.getImage(),w=image.getWidth(),h=image.getHeight(),scale=Math.min(1,2200/Math.max(w,h)),ow=Math.max(1,Math.round(w*scale)),oh=Math.max(1,Math.round(h*scale)),r=await image.readRasters({width:ow,height:oh,interleave:true,resampleMethod:'bilinear'}),samples=image.getSamplesPerPixel(),out=new Uint8ClampedArray(ow*oh*4);let min=Infinity,max=-Infinity;if(samples===1){for(const v of r){if(Number.isFinite(v)){min=Math.min(min,v);max=Math.max(max,v)}}}for(let i=0;i<ow*oh;i++){if(samples===1){const v=Math.round(255*(r[i]-min)/(max-min||1));out[i*4]=out[i*4+1]=out[i*4+2]=v}else{out[i*4]=r[i*samples];out[i*4+1]=r[i*samples+1]??r[i*samples];out[i*4+2]=r[i*samples+2]??r[i*samples]}out[i*4+3]=255}canvas.width=ow;canvas.height=oh;ctx.putImageData(new ImageData(out,ow,oh),0,0);status.textContent=w+' × '+h+' px'}catch(e){status.textContent='Falha ao abrir o COG: '+e.message}`}
  else if(asset.type==='model_3d'&&variant){module=`import*as THREE from'https://esm.sh/three@0.180.0';import{GLTFLoader}from'https://esm.sh/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';import{OrbitControls}from'https://esm.sh/three@0.180.0/examples/jsm/controls/OrbitControls.js';const host=document.querySelector('#stage'),scene=new THREE.Scene();scene.background=new THREE.Color(0x101916);const camera=new THREE.PerspectiveCamera(45,host.clientWidth/host.clientHeight,.01,1e7),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(host.clientWidth,host.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x33443e,3));const controls=new OrbitControls(camera,renderer.domElement);new GLTFLoader().load('${content}',g=>{scene.add(g.scene);const box=new THREE.Box3().setFromObject(g.scene),size=box.getSize(new THREE.Vector3()).length(),center=box.getCenter(new THREE.Vector3());controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(size*.6,size*.45,size*.6));camera.near=size/10000;camera.far=size*100;camera.updateProjectionMatrix();controls.update();document.querySelector('#status').textContent='Modelo carregado'},undefined,e=>document.querySelector('#status').textContent='Falha: '+e.message);function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop();addEventListener('resize',()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)})`}
  else if(asset.type==='photo')module=`document.querySelector('#stage').innerHTML='<img class="media" src="${content}" alt="">';document.querySelector('#status').textContent='Imagem'`;
  else if(asset.type==='video')module=`document.querySelector('#stage').innerHTML='<video class="media" src="${content}" controls></video>';document.querySelector('#status').textContent='Vídeo'`;
  else if(asset.type==='pdf'||asset.type==='document')module=`document.querySelector('#stage').innerHTML='<iframe class="media" src="${content}" title="Documento"></iframe>';document.querySelector('#status').textContent='Documento'`;
  else module=`document.querySelector('#status').textContent='A variante de visualização ainda não foi gerada.'`;
  const markup=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(asset.title)} — PJJ</title><style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;background:#0f1916;color:#fff;font:14px system-ui;overflow:hidden}.bar{height:60px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;background:#173f35}.bar h1{font-size:16px}.bar a{color:#fff}.stage{height:calc(100vh - 94px);display:grid;place-items:center;overflow:auto}.stage canvas{max-width:none;image-rendering:auto;box-shadow:0 10px 50px #0008}.media{width:100%;height:100%;object-fit:contain;border:0}.status{height:34px;padding:7px 20px;color:#b8c9c2;background:#14211d}</style></head><body><header class="bar"><h1>${esc(asset.title)}</h1><a href="${content}">Baixar original</a></header><main id="stage" class="stage"><canvas></canvas></main><footer id="status" class="status">Carregando…</footer><script type="module" nonce="${nonce}">${module}</script></body></html>`;
  const response=html(markup,nonce);response.headers.set('content-security-policy',`default-src 'none'; script-src 'nonce-${nonce}' https://esm.sh; connect-src 'self' https://esm.sh; img-src 'self' blob: data:; media-src 'self' blob:; frame-src 'self'; style-src 'nonce-${nonce}'; frame-ancestors 'self'; base-uri 'none'`);response.headers.delete('x-frame-options');return response;
}
